name: Build Docker Image

env:
  SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  packages: write
  attestations: write
  
jobs:
  test:
    name: Run tests
    runs-on: 
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build npm
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json

      - name: Install modules
        run: npm ci --ignore-scripts

      - name: Lint code
        run: npm run lint

      - name: Run tests
        timeout-minutes: 10
        run: npm test

      # - uses: act10ns/slack@v2
      #   with:
      #     status: ${{ job.status }}
      #   if: failure()

  build:
    name: Build docker image
    runs-on: 
      - self-hosted
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=short
            type=semver,pattern={{version}},prefix=
            type=semver,pattern={{major}}.{{minor}},prefix=
            type=semver,pattern={{major}},prefix=
          flavor: |
            latest=auto # only true when building from a semver tag

      - name: Ensure multi-platform image
        uses: docker/setup-buildx-action@v3
        with:
          name: vv-builder
          driver: docker-container

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      # - uses: act10ns/slack@v2
      #   with:
      #     status: ${{ job.status }}
      #   if: failure()
